-- Run this SQL in your Supabase SQL Editor to create the financial_news table

CREATE TABLE public.financial_news (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    "summaryWhatHappened" TEXT NOT NULL,
    "summaryWhoImpacted" TEXT NOT NULL,
    "summaryActionableTakeaway" TEXT NOT NULL,
    "summaryText" TEXT NOT NULL,
    category TEXT NOT NULL,
    "financialActionUrl" TEXT,
    "sourceUrl" TEXT NOT NULL,
    "sourceName" TEXT NOT NULL DEFAULT 'Indian Financial Feed',
    "audioUrl" TEXT,
    "imageUrl" TEXT,
    "financialImpactBullets" TEXT,
    "publishedAt" BIGINT,
    "isBookmarked" BOOLEAN DEFAULT FALSE,
    "readCount" INTEGER DEFAULT 1250,
    "shareCount" INTEGER DEFAULT 180
);

-- Note: Depending on your exact insert method, you may need to map Python snake_case or camelCase dict keys to the exact column names. 
-- The Python script sends exactly the camelCase keys because it was built to mirror the Kotlin Entity, so the quotes around column names above are required in PostgreSQL to preserve camelCase.

-- FIX FOR PERMISSION DENIED FOR SEQUENCE & TABLE:
-- Run these statements in your Supabase SQL Editor:

GRANT SELECT, INSERT, UPDATE, DELETE ON public.financial_news TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financial_news TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financial_news TO service_role;

-- Grant permissions on the sequence generated by SERIAL:
GRANT USAGE, SELECT ON SEQUENCE public.financial_news_id_seq TO anon, authenticated, service_role;
-- Or grant for all sequences in the public schema:
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- If Row Level Security (RLS) is enabled, either disable it or allow insert:
-- ALTER TABLE public.financial_news DISABLE ROW LEVEL SECURITY;
-- OR create a policy:
-- CREATE POLICY "Allow insert" ON public.financial_news FOR INSERT WITH CHECK (true);

